// Auto-generated by refresh-dashboard.js — 2026-05-14T12:17:48.960Z
// Do not edit manually. Run: node command-centre/refresh-dashboard.js
const DASHBOARD_DATA = {
  "refreshed": "2026-05-14T12:17:48.960Z",
  "pnl": {
    "generated": "2026-05-14T12:12:56.216Z",
    "month": "2026-05",
    "revenue": {
      "dataAsOf": "2026-05-04",
      "staleDays": 0,
      "groupEstimate": 31680,
      "ptEstimate": 152250,
      "activeMembers": 73,
      "totalEstimate": 183930
    },
    "costs": {
      "rent": 52000,
      "cleaning": 3000,
      "insurance": 2000,
      "mpf": 1500,
      "utilities": 2000,
      "misc": 1500
    },
    "totalCosts": 62000,
    "netIncome": 121930,
    "profitable": true,
    "note": "Revenue is estimated from member count. For actual P&L, Paul inputs PunchPass revenue report figures."
  },
  "commission": {
    "generated": "2026-05-14T12:12:55.631Z",
    "dataAsOf": "2026-05-04",
    "dataStaleDays": 0,
    "totalActiveMembers": 73,
    "passBreakdown": {
      "unlimited": 0,
      "pack": 20,
      "PT": 29,
      "trial": 12,
      "drop_in": 10,
      "kids": 1,
      "bootcamp": 0,
      "other": 1
    },
    "revenue": {
      "estimatedGroupMonthly": 31680,
      "estimatedPTMonthly": 152250,
      "estimatedTotalMonthly": 183930,
      "note": "Estimates based on member count × average rates. Actual from PunchPass revenue report."
    },
    "commission": {
      "groupPerHead": 90,
      "ptRate": "50%",
      "estimatedGroupCommission": 15840,
      "estimatedPTCommission": 76125,
      "note": "Coach assignment not tracked in PunchPass. Paul assigns manually."
    },
    "coaches": {
      "aman": {
        "name": "Aman",
        "active": false,
        "lastDay": "2026-06-11"
      },
      "paul": {
        "name": "Paul",
        "active": true,
        "isOwner": true
      }
    }
  },
  "memberSummary": {
    "total": 73,
    "churnRiskMedium": 1,
    "churnRiskHigh": 21,
    "expiringSoon": 23,
    "dataAsOf": "2026-05-04"
  },
  "pm2": {
    "online": 18,
    "stopped": 27,
    "total": 45,
    "critical": [
      {
        "name": "cathedral-bot",
        "status": "online"
      },
      {
        "name": "cath-bridge",
        "status": "online"
      },
      {
        "name": "vault-watcher",
        "status": "online"
      },
      {
        "name": "sentinel",
        "status": "online"
      }
    ]
  },
  "mpf": {
    "nextDeadline": "2026-06-10",
    "daysUntilDeadline": 27,
    "alerts": 1
  },
  "hrAlerts": 0,
  "workstreams": [
    {
      "phase": 0,
      "name": "Curriculum",
      "desc": "10-Block system documented + config wired",
      "status": "done",
      "icon": "📖"
    },
    {
      "phase": 1,
      "name": "Operations",
      "desc": "Finance, HR, compliance, scheduling",
      "status": "done",
      "icon": "⚙️"
    },
    {
      "phase": 2,
      "name": "Dashboard",
      "desc": "KPI dashboard + command centre",
      "status": "active",
      "icon": "📊"
    },
    {
      "phase": 3,
      "name": "Client Comms",
      "desc": "WhatsApp templates, comms queue, approval gate",
      "status": "planned",
      "icon": "💬"
    },
    {
      "phase": 4,
      "name": "Growth + Maya",
      "desc": "Content pipeline, social voice, IG strategy",
      "status": "planned",
      "icon": "🚀"
    },
    {
      "phase": 5,
      "name": "Merch Agent",
      "desc": "Design, sourcing, inventory, milestone rewards",
      "status": "planned",
      "icon": "👕"
    }
  ],
  "peakRevenue": 933030,
  "currentAnnualised": 2207160,
  "lapsedMembers": 566
};
